[[pages]]
path = "MBA_App.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "others/page2.py"
name = "Exploratory Data Analysis"
icon = "âš½"

[[pages]]
path = "others/page3.py"
name = "Market Basket Analysis"
icon = "ğŸ‘œ"

[[pages]]
path = "others/page4.py"
name = "Customer Segmentation"
icon = "ğŸ‘œ"

[[pages]]
path = "others/page5.py"
name = "Product Recommentation"
icon = "ğŸ‘œ"
